export type NavItem = { slug: string; label: string };
export type NavGroup = { label: string; items: NavItem[] };

export const componentNav: NavGroup[] = [
  {
    label: "Motion",
    items: [
      { slug: "reveal", label: "Reveal" },
      { slug: "page-transition", label: "Page Transition" },
    ],
  },
  {
    label: "Primitives",
    items: [
      { slug: "announcement", label: "Announcement" },
      { slug: "avatar", label: "Avatar" },
      { slug: "avatar-group", label: "Avatar Group" },
      { slug: "badge", label: "Badge" },
      { slug: "button", label: "Button" },
      { slug: "card", label: "Card" },
      { slug: "checkbox", label: "Checkbox" },
      { slug: "chip", label: "Chip" },
      { slug: "dialog", label: "Dialog" },
      { slug: "drawer", label: "Drawer" },
      { slug: "dropdown-menu", label: "Dropdown Menu" },
      { slug: "hint-popover", label: "Hint Popover" },
      { slug: "icon-button", label: "Icon Button" },
      { slug: "input", label: "Input" },
      { slug: "label", label: "Label" },
      { slug: "list", label: "List" },
      { slug: "loading-overlay", label: "Loading Overlay" },
      { slug: "log-line", label: "Log Line" },
      { slug: "notification-badge", label: "Notification Badge" },
      { slug: "popover", label: "Popover" },
      { slug: "progress", label: "Progress" },
      { slug: "radio", label: "Radio" },
      { slug: "select", label: "Select" },
      { slug: "skeleton", label: "Skeleton" },
      { slug: "spinner", label: "Spinner" },
      { slug: "stat-chip", label: "Stat Chip" },
      { slug: "switch", label: "Switch" },
      { slug: "tabs", label: "Tabs" },
      { slug: "toast", label: "Toast" },
      { slug: "tooltip", label: "Tooltip" },
    ],
  },
  {
    label: "Patterns",
    items: [
      { slug: "bento-grid", label: "Bento Grid" },
      { slug: "panel", label: "Panel" },
      { slug: "section-label", label: "Section Label" },
      { slug: "stat-card", label: "Stat Card" },
      { slug: "stripe-card", label: "Stripe Card" },
      { slug: "step-list", label: "Step List" },
      { slug: "feature-carousel", label: "Feature Carousel" },
      { slug: "empty-state", label: "Empty State" },
      { slug: "field-group", label: "Field Group" },
      { slug: "entity-card", label: "Entity Card" },
      { slug: "toolbar", label: "Toolbar" },
      { slug: "segmented-control", label: "Segmented Control" },
      { slug: "progress-row", label: "Progress Row" },
      { slug: "mockup-showcase", label: "Mockup Showcase" },
      { slug: "section-heading", label: "Section Heading" },
      { slug: "pullquote", label: "Pullquote" },
      { slug: "stat-bento", label: "Stat Bento" },
      { slug: "case-study-hero", label: "Case Study Hero" },
      { slug: "checklist-card", label: "Checklist Card" },
      { slug: "step-chips", label: "Step Chips" },
      { slug: "cta-banner", label: "CTA Banner" },
    ],
  },
];
