import { Badge, Card, CardBody, CardHeader } from "@matt-pasek/usva";
import type { Metadata } from "next";
import { buildTokenReference } from "@/lib/token-reference";

export const metadata: Metadata = {
  title: "Design language",
  description:
    "usva.'s principles, voice, and an auto-generated reference of every token — beauty that stays usable.",
};

const principles = [
  {
    title: "Beauty that stays usable",
    body: "The thesis. Both consumer apps — the presentational kajo pole and the usable sisu pole — map onto one token vocabulary. Neither wins at the other's expense.",
  },
  {
    title: "Role-based tokens, never raw values",
    body: "Every color, space, radius, and duration is consumed by semantic role — accent, surface, danger — never as a hardcoded hex or pixel. Themes swap; call sites don't change.",
  },
  {
    title: "Two accents, paired",
    body: "usva pairs a design accent and a dev accent everywhere the language shows its own construction — never one alone.",
    accentPair: true,
  },
  {
    title: "A11y-first",
    body: "Contrast, focus rings, and reduced-motion fallbacks are load-bearing, not polish passed at the end.",
  },
  {
    title: "Restrained spring motion",
    body: "Motion earns its keep: soft entrances, snappy feedback, nothing bouncy enough to distract from the task underneath.",
  },
];

const voicePoints = [
  "first-person, lowercase-leaning — usva. speaks as itself, not as marketing copy",
  "confident but unshowy: a belief stated plainly, then earned with the work that follows",
  "keywords get an accent tint, not bold — color carries weight the way tokens do",
  "no emoji — the accent system already does the emphasis emoji would fake",
  "→ over arrow words, when an affordance genuinely needs pointing at",
  "numbers are honest: no invented precision, no rounding up",
];

export default function DesignLanguagePage() {
  const tokens = buildTokenReference();

  return (
    <main className="mx-auto flex max-w-3xl flex-col gap-12 p-10">
      <header className="flex flex-col gap-3">
        <Badge tone="accent">design language</Badge>
        <h1 className="text-3xl font-semibold text-ink">
          beauty that stays usable
        </h1>
        <p className="max-w-xl text-muted">
          usva. is a design <em>language</em> before it's a component library —
          principles and voice, then tokens, then the primitives that carry
          them. This page is the first written slice of it: the principles
          below, a voice summary, and a token reference generated straight from
          the tokens package, so it can never drift.
        </p>
      </header>

      <section className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold text-ink">Principles</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {principles.map((p) => (
            <Card key={p.title}>
              <CardHeader>
                {p.accentPair ? (
                  <span>
                    <span className="text-accent">Two</span> accents,{" "}
                    <span className="text-success">paired</span>
                  </span>
                ) : (
                  p.title
                )}
              </CardHeader>
              <CardBody className="text-sm text-muted">{p.body}</CardBody>
            </Card>
          ))}
        </div>
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold text-ink">Voice summary</h2>
        <Card>
          <CardBody>
            <ul className="flex flex-col gap-2 text-sm text-muted">
              {voicePoints.map((point) => (
                <li key={point} className="flex gap-2">
                  <span className="text-accent">→</span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4 text-xs text-faint">
              Full Voice &amp; Tone reference lands in Phase 4.
            </p>
          </CardBody>
        </Card>
      </section>

      <section className="flex flex-col gap-6">
        <div className="flex flex-col gap-2">
          <h2 className="text-xl font-semibold text-ink">Token reference</h2>
          <p className="text-sm text-muted">
            Generated by <code>buildTokenReference()</code> from the tokens
            package's own exports — nothing here is hand-transcribed.
          </p>
        </div>

        <Card>
          <CardHeader>Color roles</CardHeader>
          <CardBody>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {tokens.color.map(({ name }) => (
                <div key={name} className="flex items-center gap-2">
                  <div
                    className={`h-8 w-8 shrink-0 rounded-md border border-border bg-${name}`}
                  />
                  <span className="font-mono text-xs text-muted">{name}</span>
                </div>
              ))}
            </div>
          </CardBody>
        </Card>

        <Card>
          <CardHeader>Spacing scale</CardHeader>
          <CardBody>
            <div className="flex flex-col gap-1.5">
              {tokens.spacing.map(({ name, value }) => (
                <div key={name} className="flex items-center gap-3">
                  <span className="w-10 shrink-0 font-mono text-xs text-muted">
                    {name}
                  </span>
                  <div
                    className="h-2 rounded-full bg-accent"
                    style={{ width: value }}
                  />
                  <span className="font-mono text-xs text-faint">{value}</span>
                </div>
              ))}
            </div>
          </CardBody>
        </Card>

        <div className="grid gap-4 sm:grid-cols-2">
          <Card>
            <CardHeader>Radius</CardHeader>
            <CardBody>
              <div className="flex flex-col gap-3">
                {tokens.radius.map(({ name, value }) => (
                  <div key={name} className="flex items-center gap-3">
                    <div
                      className="h-8 w-8 shrink-0 border border-border-strong bg-surface-2"
                      style={{ borderRadius: value }}
                    />
                    <span className="font-mono text-xs text-muted">{name}</span>
                    <span className="font-mono text-xs text-faint">
                      {value}
                    </span>
                  </div>
                ))}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardHeader>Motion durations</CardHeader>
            <CardBody>
              <div className="flex flex-col gap-2">
                {tokens.motion.map(({ name, value }) => (
                  <div
                    key={name}
                    className="flex items-center justify-between font-mono text-xs"
                  >
                    <span className="text-muted">{name}</span>
                    <span className="text-faint">{value}</span>
                  </div>
                ))}
              </div>
            </CardBody>
          </Card>
        </div>

        <Card>
          <CardHeader>Type ramp</CardHeader>
          <CardBody>
            <div className="flex flex-col gap-3">
              {tokens.type.map(({ name, value }) => (
                <div key={name} className="flex items-baseline gap-4">
                  <span className="w-10 shrink-0 font-mono text-xs text-muted">
                    {name}
                  </span>
                  <span className="text-ink" style={{ fontSize: value }}>
                    usva.
                  </span>
                  <span className="font-mono text-xs text-faint">{value}</span>
                </div>
              ))}
            </div>
          </CardBody>
        </Card>
      </section>
    </main>
  );
}
